// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADRq8DGoEw4Y-8JMbyUiw8cW6g6N-x97c',
    appId: '1:48297602368:web:cff2b96e49546810771ea5',
    messagingSenderId: '48297602368',
    projectId: 'weekenddoit-6d41e',
    authDomain: 'weekenddoit-6d41e.firebaseapp.com',
    storageBucket: 'weekenddoit-6d41e.firebasestorage.app',
    measurementId: 'G-ZS5MMPFCK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfpRNzDWxoP7E0alJNlrQVChRdZ4jrkgo',
    appId: '1:48297602368:android:501b77c544b15521771ea5',
    messagingSenderId: '48297602368',
    projectId: 'weekenddoit-6d41e',
    storageBucket: 'weekenddoit-6d41e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL9ch01E2Ms4qeeBksOmjjHvc-GUaQhqc',
    appId: '1:48297602368:ios:836f3a83c6b2da75771ea5',
    messagingSenderId: '48297602368',
    projectId: 'weekenddoit-6d41e',
    storageBucket: 'weekenddoit-6d41e.firebasestorage.app',
    iosBundleId: 'com.weekenddoit.now',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL9ch01E2Ms4qeeBksOmjjHvc-GUaQhqc',
    appId: '1:48297602368:ios:836f3a83c6b2da75771ea5',
    messagingSenderId: '48297602368',
    projectId: 'weekenddoit-6d41e',
    storageBucket: 'weekenddoit-6d41e.firebasestorage.app',
    iosBundleId: 'com.weekenddoit.now',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADRq8DGoEw4Y-8JMbyUiw8cW6g6N-x97c',
    appId: '1:48297602368:web:bab70ba7c0697f0a771ea5',
    messagingSenderId: '48297602368',
    projectId: 'weekenddoit-6d41e',
    authDomain: 'weekenddoit-6d41e.firebaseapp.com',
    storageBucket: 'weekenddoit-6d41e.firebasestorage.app',
    measurementId: 'G-BTZNSCVVVJ',
  );
}
